apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yml
  - service.yml
  - ingress.yml
configMapGenerator:
  - name: app-config
    files:
      - config.properties
secretGenerator:
  - name: app-secrets
    envs:
      - secrets.env
images:
  - name: myapp
    newTag: v1.0.0
commonLabels:
  app: myapp
  env: production
