apiVersion: v1
kind: ConfigMap
metadata:
  name: debian-config
data:
  DEBIAN_FRONTEND: "noninteractive"
  TZ: "UTC"
  LANG: "en_US.UTF-8"
  LC_ALL: "en_US.UTF-8"
  PATH: "/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
