apiVersion: v1
kind: Service
metadata:
  name: debian-service
spec:
  selector:
    app: debian
  ports:
  - protocol: TCP
    port: 22
    targetPort: 22
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: centos-service
spec:
  selector:
    app: centos
  ports:
  - protocol: TCP
    port: 22
    targetPort: 22
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: alpine-service
spec:
  selector:
    app: alpine
  ports:
  - protocol: TCP
    port: 22
    targetPort: 22
  type: ClusterIP
