---
# Ubuntu Storage Configuration
include: base_storage_config.yaml

storage_config:
  package_dependencies:
    - lvm2
    - xfsprogs
    - btrfs-progs
    
  fstab_options:
    root:
      options: ["errors=remount-ro", "noatime"]
    swap:
      options: ["sw", "pri=1"]
      
  disk_encryption:
    type: "luks2"
    options:
      cipher: "aes-xts-plain64"
      key_size: 512
      hash: "sha512"
      
  swap:
    type: "partition"  # or "file"
    size: "equal_to_ram"
    file_location: "/swapfile"  # if type is "file"
    
  maintenance:
    trim_schedule: "weekly"
    fsck_schedule: "monthly"
    smart_monitoring: true
