gcp:
  regions:
    - us-central1
    - us-east1
  machine_types:
    - e2-micro
    - e2-small
    - e2-medium
  os_configurations:
    ubuntu2004:
      project: ubuntu-os-cloud
      family: ubuntu-2004-lts
    debian11:
      project: debian-cloud
      family: debian-11
    centos7:
      project: centos-cloud
      family: centos-7
    rhel8:
      project: rhel-cloud
      family: rhel-8
