apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: custom-cluster-admin
subjects:
- kind: Group
  name: system:masters
  apiGroup: rbac.authorization.k8s.io
- kind: ServiceAccount
  name: admin-service-account
  namespace: kube-system
roleRef:
  kind: ClusterRole
  name: custom-cluster-admin
  apiGroup: rbac.authorization.k8s.io
