global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'user-service'
    static_configs:
      - targets: ['user-service:8081']

  - job_name: 'product-service'
    static_configs:
      - targets: ['product-service:8082']

  - job_name: 'order-service'
    static_configs:
      - targets: ['order-service:8083']

  - job_name: 'api-gateway'
    static_configs:
      - targets: ['api-gateway:8080']

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
