---
collections:
  - name: amazon.aws
    version: ">=2.0.0"
  - name: azure.azcollection
    version: ">=1.0.0"
  - name: google.cloud
    version: ">=1.0.0"
  - name: community.general
    version: ">=3.0.0"
  - name: ansible.posix
    version: ">=1.0.0"

roles:
  - src: geerlingguy.docker
    version: "3.1.2"
  - src: geerlingguy.nginx
    version: "3.1.3"
  - src: geerlingguy.postgresql
    version: "3.4.2"
  - src: dev-sec.os-hardening
    version: "7.0.0"
  - src: dev-sec.ssh-hardening
    version: "9.8.0"
